SET "DESIRED_PATH=%~1"

for /f "tokens=2* delims= " %%A in ('reg query "HKCU\Environment" /v PATH 2^>nul') do (
    SET SYSTEM_PATH="%%B"
)
CALL SET SYSTEM_PATH=%SYSTEM_PATH%
IF NOT defined SYSTEM_PATH SET SYSTEM_PATH=""
SET "SYSTEM_PATH=%SYSTEM_PATH:"=%"

ECHO %SYSTEM_PATH% | find /I "%DESIRED_PATH%" >nul
if %ERRORLEVEL%==0 GOTO :EOF
SETX PATH "%DESIRED_PATH%;%SYSTEM_PATH%"
